# Perfil `api`: expone HTTP en el puerto 8000.
server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/redis_workshop
    username: redisworkshop
    password: redisworkshop
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  cache:
    type: redis
    cache-names: products
    redis:
      time-to-live: 60s
      enable-statistics: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
